import { defineAsyncComponent } from 'vue'

// components
const DashNavbar = defineAsyncComponent(() => import('../components/DashNavbar.vue'))
const Footer = defineAsyncComponent(() => import('../components/Footer.vue'))
const SingleSelect = defineAsyncComponent(() => import('../components/Dropdown/SingleSelect.vue'))
const MultiSelect = defineAsyncComponent(() => import('../components/Dropdown/MultiSelect.vue'))
const Loader = defineAsyncComponent(() => import('../components/Loader.vue'))
const Modal = defineAsyncComponent(() => import('../components/Modal.vue'))
const Alert = defineAsyncComponent(() => import('../components/Alert.vue'))
const EventCalender = defineAsyncComponent(() => import('../components/EventCalender.vue'))
const AptSuccessModal = defineAsyncComponent(() => import('../components/Modals/AptSuccessModal.vue'))
// const  = defineAsyncComponent(() => import('../components/.vue'))

//Lab Test
const AddTestModal = defineAsyncComponent(() => import('../components/Labtest/AddTestModal.vue'))
const AddPanelModal = defineAsyncComponent(() => import('../components/Labtest/AddPanelModal.vue'))
const AddPackageModal = defineAsyncComponent(() => import('../components/Labtest/AddPackageModal.vue'))
const AddTemplateModal = defineAsyncComponent(() => import('../components/Labtest/AddTemplateModal.vue'))

//Doctor Profile
const DoctorProfile = defineAsyncComponent(() => import('../components/DoctorProfile/Profile.vue'))
const DoctorEducation = defineAsyncComponent(() => import('../components/DoctorProfile/Education.vue'))
const DoctorExpertise = defineAsyncComponent(() => import('../components/DoctorProfile/Expertise.vue'))
const DoctorLanguage = defineAsyncComponent(() => import('../components/DoctorProfile/Language.vue'))
const DoctorFees = defineAsyncComponent(() => import('../components/DoctorProfile/Fees.vue'))
const DoctorSign = defineAsyncComponent(() => import('../components/DoctorProfile/Sign.vue'))
const DoctorBlock = defineAsyncComponent(() => import('../components/DoctorProfile/Block.vue'))
const DoctorSchedule = defineAsyncComponent(() => import('../components/DoctorProfile/Schedule.vue'))

//icons
const RightArrowIcon = defineAsyncComponent(() => import('../components/icons/right-arrow-svg.vue'))
const LoginLoaderIcon = defineAsyncComponent(() => import('../components/icons/login-loader-svg.vue'))
const CalenderIcon = defineAsyncComponent(() => import('../components/icons/calender-svg.vue'))
const CrossIcon = defineAsyncComponent(() => import('../components/icons/cross-svg.vue'))
const SearchIcon = defineAsyncComponent(() => import('../components/icons/search-svg.vue'))
const MailIcon = defineAsyncComponent(() => import('../components/icons/mail-svg.vue'))
const LocationIcon = defineAsyncComponent(() => import('../components/icons/location-svg.vue'))
const PhoneIcon = defineAsyncComponent(() => import('../components/icons/phone-svg.vue'))
const SuccessIcon = defineAsyncComponent(() => import('../components/icons/success-svg.vue'))
const WarningIcon = defineAsyncComponent(() => import('../components/icons/warning-svg.vue'))
const MenuIcon = defineAsyncComponent(() => import('../components/icons/menu-svg.vue'))
const DoubleArrowIcon = defineAsyncComponent(() => import('../components/icons/double-arrow-svg.vue'))
const PadIcon = defineAsyncComponent(() => import('../components/icons/pad-svg.vue'))
const DoctorIcon = defineAsyncComponent(() => import('../components/icons/doctor-svg.vue'))
const NurseIcon = defineAsyncComponent(() => import('../components/icons/nurse-svg.vue'))
const HospitalIcon = defineAsyncComponent(() => import('../components/icons/hospital-svg.vue'))
const RightArrowRoundIcon = defineAsyncComponent(() => import('../components/icons/right-arrow-round-svg.vue'))
const DownArrowRoundIcon = defineAsyncComponent(() => import('../components/icons/down-arrow-round-svg.vue'))
const MessageIcon = defineAsyncComponent(() => import('../components/icons/message-svg.vue'))
const UserIcon = defineAsyncComponent(() => import('../components/icons/user-svg.vue'))
const TwitterIcon = defineAsyncComponent(() => import('../components/icons/twitter-svg.vue'))
const InstagramIcon = defineAsyncComponent(() => import('../components/icons/instagram-svg.vue'))
const FacebookIcon = defineAsyncComponent(() => import('../components/icons/facebook-svg.vue'))
const GoogleIcon = defineAsyncComponent(() => import('../components/icons/google-svg.vue'))
const LinkedinIcon = defineAsyncComponent(() => import('../components/icons/linkedin-svg.vue'))
const TelegramIcon = defineAsyncComponent(() => import('../components/icons/telegram-svg.vue'))
const StarIcon = defineAsyncComponent(() => import('../components/icons/star-svg.vue'))
const QuoteIcon = defineAsyncComponent(() => import('../components/icons/quote-svg.vue'))
const LoginIcon = defineAsyncComponent(() => import('../components/icons/login-svg.vue'))
const Notification = defineAsyncComponent(() => import('../components/Notification.vue'));
const NotificationList = defineAsyncComponent(() => import('../components/NotificationList.vue'));
const NotificationMessage = defineAsyncComponent(() => import('../components/NotificationMessage.vue'));
const spinner = defineAsyncComponent(() => import('../components/Spinner.vue'));
const MobileIcon = defineAsyncComponent(() => import('../components/icons/mobile-svg.vue'))
const LeftArrowIcon = defineAsyncComponent(() => import('../components/icons/left-arrow-svg.vue'))
const NoteIcon = defineAsyncComponent(() => import('../components/icons/note-svg.vue'))
const AddIcon = defineAsyncComponent(() => import('../components/icons/add-svg.vue'))
const DeleteIcon = defineAsyncComponent(() => import('../components/icons/delete-svg.vue'))
const EditIcon = defineAsyncComponent(() => import('../components/icons/edit-svg.vue'))
const VertDotsIcon = defineAsyncComponent(() => import('../components/icons/vert-dots-svg.vue'))
const AddUserIcon = defineAsyncComponent(() => import('../components/icons/add-user-svg.vue'))
// const Icon = defineAsyncComponent(() => import('../components/icons/-svg.vue'))

const GlobalComponents = {
  install (app) {
    app.component('DashNavbar', DashNavbar)
    app.component('Footer', Footer)
    app.component('SingleSelect', SingleSelect)
    app.component('MultiSelect', MultiSelect)
    app.component('Loader', Loader)
    app.component('Modal', Modal)
    app.component('Alert', Alert)
    app.component('EventCalender', EventCalender)
    app.component('AptSuccessModal', AptSuccessModal)
    // app.component('', )

    //Lab Test
    app.component('AddTestModal', AddTestModal)
    app.component('AddPanelModal', AddPanelModal)
    app.component('AddPackageModal', AddPackageModal)
    app.component('AddTemplateModal', AddTemplateModal)

    //Doctor Profile
    app.component('DoctorProfile', DoctorProfile)
    app.component('DoctorEducation', DoctorEducation)
    app.component('DoctorExpertise', DoctorExpertise)
    app.component('DoctorLanguage', DoctorLanguage)
    app.component('DoctorFees', DoctorFees)
    app.component('DoctorSign', DoctorSign)
    app.component('DoctorBlock', DoctorBlock)
    app.component('DoctorSchedule', DoctorSchedule)
    
    // icons
    app.component('icon-right-arrow', RightArrowIcon)
    app.component('icon-login-loader', LoginLoaderIcon)
    app.component('icon-calender', CalenderIcon)
    app.component('icon-cross', CrossIcon)
    app.component('icon-search', SearchIcon)
    app.component('icon-mail', MailIcon)
    app.component('icon-location', LocationIcon)
    app.component('icon-phone', PhoneIcon)
    app.component('icon-success', SuccessIcon)
    app.component('icon-warning', WarningIcon)
    app.component('icon-menu', MenuIcon)
    app.component('icon-double-arrow', DoubleArrowIcon)
    app.component('icon-pad', PadIcon)
    app.component('icon-doctor', DoctorIcon)
    app.component('icon-nurse', NurseIcon)
    app.component('icon-hospital', HospitalIcon)
    app.component('icon-right-arrow-round', RightArrowRoundIcon)
    app.component('icon-down-arrow-round', DownArrowRoundIcon)
    app.component('icon-message', MessageIcon)
    app.component('icon-user', UserIcon)
    app.component('icon-twitter', TwitterIcon)
    app.component('icon-instagram', InstagramIcon)
    app.component('icon-facebook', FacebookIcon)
    app.component('icon-google', GoogleIcon)
    app.component('icon-linkedin', LinkedinIcon)
    app.component('icon-telegram', TelegramIcon)
    app.component('icon-star', StarIcon)
    app.component('icon-quote', QuoteIcon)
    app.component('icon-login', LoginIcon)
    app.component('Notification', Notification)
		app.component('Notification-list', NotificationList)
		app.component('Notification-message', NotificationMessage)
    app.component('base-spinner', spinner);
    app.component('icon-mobile', MobileIcon)
    app.component('icon-left-arrow', LeftArrowIcon)
    app.component('icon-note', NoteIcon)
    app.component('icon-add', AddIcon)
    app.component('icon-delete', DeleteIcon)
    app.component('icon-edit', EditIcon)
    app.component('icon-vert-dots', VertDotsIcon)
    app.component('icon-add-user', AddUserIcon)
    // app.component('icon-', Icon)
  }
}

export default GlobalComponents
